import Foundation

let sampleContent = ContentResponse(
    content: [
        // Movies
        ContentItem(
            id: "1",
            type: .movie,
            title: "CODA",
            releaseDate: "August 13, 2021",
            age: 12,
            rating: Rating(imdb: 8.1),
            genres: ["Drama", "Music"],
            summary: "A teenage girl, the only hearing member of a deaf family, struggles between her passion for music and family obligations.",
            imageAssets: ImageAssets(poster: "coda_poster"),
            cast: ["Emilia Jones", "Troy Kotsur", "Marlee Matlin"],
            director: ["Sian Heder"],
            platform: "Apple TV+"
        ),
        ContentItem(
            id: "2",
            type: .movie,
            title: "Don’t Look Up",
            releaseDate: "December 10, 2021",
            age: 12,
            rating: Rating(imdb: 7.2),
            genres: ["Comedy", "Drama", "Sci-Fi"],
            summary: "Two astronomers try to warn humanity of an approaching comet that will destroy Earth.",
            imageAssets: ImageAssets(poster: "dontlookup_poster"),
            cast: ["Leonardo DiCaprio", "Jennifer Lawrence", "Meryl Streep"],
            director: ["Adam McKay"],
            platform: "Netflix"
        ),
        ContentItem(
            id: "3",
            type: .movie,
            title: "The Gray Man",
            releaseDate: "July 22, 2022",
            age: 16,
            rating: Rating(imdb: 6.5),
            genres: ["Action", "Thriller"],
            summary: "A top CIA asset goes rogue after uncovering dark agency secrets, pursued by assassins worldwide.",
            imageAssets: ImageAssets(poster: "thegrayman_poster"),
            cast: ["Ryan Gosling", "Chris Evans", "Ana de Armas"],
            director: ["Anthony Russo", "Joe Russo"],
            platform: "Netflix"
        ),
        ContentItem(
            id: "4",
            type: .movie,
            title: "The Irishman",
            releaseDate: "November 1, 2019",
            age: 16,
            rating: Rating(imdb: 7.8),
            genres: ["Crime", "Drama"],
            summary: "A hitman reflects on his life and involvement in the disappearance of Jimmy Hoffa.",
            imageAssets: ImageAssets(poster: "theirishman_poster"),
            cast: ["Robert De Niro", "Al Pacino", "Joe Pesci"],
            director: ["Martin Scorsese"],
            platform: "Netflix"
        ),
        ContentItem(
            id: "5",
            type: .movie,
            title: "The Pale Blue Eye",
            releaseDate: "December 23, 2022",
            age: 16,
            rating: Rating(imdb: 6.6),
            genres: ["Mystery", "Thriller"],
            summary: "A detective investigates a series of murders at West Point Academy, assisted by Edgar Allan Poe.",
            imageAssets: ImageAssets(poster: "thepaleblueeye_poster"),
            cast: ["Christian Bale", "Harry Melling", "Gillian Anderson"],
            director: ["Scott Cooper"],
            platform: "Netflix"
        ),
        ContentItem(
            id: "16",
            type: .movie,
            title: "Killers of the Flower Moon",
            releaseDate: "October 20, 2023",
            age: 16,
            rating: Rating(imdb: 7.5),
            genres: ["Crime", "Drama", "Mystery"],
            summary: "Investigates the mysterious murders of wealthy Osage Native Americans in the 1920s, uncovering a conspiracy and birth of the FBI.",
            imageAssets: ImageAssets(poster: "killersoftheflowermoon_poster"),
            cast: ["Leonardo DiCaprio", "Robert De Niro", "Lily Gladstone"],
            director: ["Martin Scorsese"],
            platform: "Apple TV+"
        ),
        ContentItem(
            id: "17",
            type: .movie,
            title: "Glass Onion: A Knives Out Mystery",
            releaseDate: "December 23, 2022",
            age: 12,
            rating: Rating(imdb: 7.2),
            genres: ["Comedy", "Crime", "Drama"],
            summary: "Detective Benoit Blanc travels to Greece to peel back the layers of a mystery involving a new cast of colorful suspects.",
            imageAssets: ImageAssets(poster: "glassonion_poster"),
            cast: ["Daniel Craig", "Edward Norton", "Janelle Monáe"],
            director: ["Rian Johnson"],
            platform: "Netflix"
        ),
        ContentItem(
            id: "18",
            type: .movie,
            title: "Bird Box",
            releaseDate: "December 14, 2018",
            age: 16,
            rating: Rating(imdb: 6.6),
            genres: ["Drama", "Horror", "Sci-Fi"],
            summary: "A woman and her two children navigate a post-apocalyptic world while blindfolded to escape supernatural entities that cause people to commit suicide.",
            imageAssets: ImageAssets(poster: "birdbox_poster"),
            cast: ["Sandra Bullock", "Trevante Rhodes", "John Malkovich"],
            director: ["Susanne Bier"],
            platform: "Netflix"
        ),
        ContentItem(
            id: "19",
            type: .movie,
            title: "The Adam Project",
            releaseDate: "March 11, 2022",
            age: 12,
            rating: Rating(imdb: 6.7),
            genres: ["Action", "Adventure", "Comedy"],
            summary: "A time-traveling pilot teams up with his younger self and his late father to come to terms with his past while saving the future.",
            imageAssets: ImageAssets(poster: "theadamproject_poster"),
            cast: ["Ryan Reynolds", "Walker Scobell", "Jennifer Garner"],
            director: ["Shawn Levy"],
            platform: "Netflix"
        ),

        // Series
        ContentItem(
            id: "6",
            type: .series,
            title: "Ted Lasso",
            releaseDate: "August 14, 2020",
            age: 12,
            rating: Rating(imdb: 8.8),
            genres: ["Comedy", "Drama", "Sport"],
            summary: "An American football coach is hired to manage an English soccer team, despite having no experience.",
            imageAssets: ImageAssets(poster: "tedlasso_poster"),
            cast: ["Jason Sudeikis", "Hannah Waddingham", "Brett Goldstein"],
            director: ["Declan Lowney", "M.J. Delaney"],
            platform: "Apple TV+"
        ),
        ContentItem(
            id: "7",
            type: .series,
            title: "Severance",
            releaseDate: "February 18, 2022",
            age: 16,
            rating: Rating(imdb: 8.5),
            genres: ["Drama", "Mystery", "Sci-Fi"],
            summary: "Employees undergo a procedure that separates their work and personal memories.",
            imageAssets: ImageAssets(poster: "severance_poster"),
            cast: ["Adam Scott", "Patricia Arquette", "John Turturro"],
            director: ["Ben Stiller"],
            platform: "Apple TV+"
        ),
        ContentItem(
            id: "8",
            type: .series,
            title: "Wednesday",
            releaseDate: "November 23, 2022",
            age: 12,
            rating: Rating(imdb: 8.0),
            genres: ["Mystery", "Comedy", "Horror"],
            summary: "Wednesday Addams investigates supernatural mysteries at Nevermore Academy while dealing with her family's legacy.",
            imageAssets: ImageAssets(poster: "wednesday_poster"),
            cast: ["Jenna Ortega", "Catherine Zeta-Jones", "Luis Guzmán"],
            director: ["Tim Burton"],
            platform: "Netflix"
        ),
        ContentItem(
            id: "9",
            type: .series,
            title: "Squid Game",
            releaseDate: "September 17, 2021",
            age: 16,
            rating: Rating(imdb: 8.0),
            genres: ["Thriller", "Drama", "Survival"],
            summary: "Hundreds of contestants accept a strange invitation to compete in children's games for a tempting prize, but the stakes are deadly.",
            imageAssets: ImageAssets(poster: "squidgame_poster"),
            cast: ["Lee Jung-jae", "Park Hae-soo", "Wi Ha-joon"],
            director: ["Hwang Dong-hyuk"],
            platform: "Netflix"
        ),
        ContentItem(
            id: "10",
            type: .series,
            title: "Stranger Things",
            releaseDate: "July 15, 2016",
            age: 12,
            rating: Rating(imdb: 8.7),
            genres: ["Sci-Fi", "Horror", "Drama"],
            summary: "A group of young friends in the 1980s uncover government conspiracies and supernatural events in their small town.",
            imageAssets: ImageAssets(poster: "strangerthings_poster"),
            cast: ["Winona Ryder", "David Harbour", "Millie Bobby Brown"],
            director: ["Duffer Brothers"],
            platform: "Netflix"
        ),
        ContentItem(
            id: "11",
            type: .series,
            title: "Foundation",
            releaseDate: "September 24, 2021",
            age: 12,
            rating: Rating(imdb: 7.4),
            genres: ["Sci-Fi", "Drama"],
            summary: "A band of exiles on their monumental journey to save humanity and rebuild civilization amid the fall of the Galactic Empire.",
            imageAssets: ImageAssets(poster: "foundation_poster"),
            cast: ["Jared Harris", "Lee Pace", "Lou Llobell"],
            director: ["David S. Goyer", "Josh Friedman"],
            platform: "Apple TV+"
        ),
        ContentItem(
            id: "12",
            type: .series,
            title: "The Morning Show",
            releaseDate: "November 1, 2019",
            age: 16,
            rating: Rating(imdb: 8.4),
            genres: ["Drama"],
            summary: "An inside look at the lives of the people who help America wake up, exploring the unique challenges faced by the team of a morning news show.",
            imageAssets: ImageAssets(poster: "themorningshow_poster"),
            cast: ["Jennifer Aniston", "Reese Witherspoon", "Steve Carell"],
            director: ["Mimi Leder"],
            platform: "Apple TV+"
        ),
        ContentItem(
            id: "14",
            type: .series,
            title: "The Crown",
            releaseDate: "November 4, 2016",
            age: 12,
            rating: Rating(imdb: 8.7),
            genres: ["Drama", "History"],
            summary: "A dramatized account of Queen Elizabeth II's reign, from her wedding in 1947 to the early 21st century.",
            imageAssets: ImageAssets(poster: "thecrown_poster"),
            cast: ["Claire Foy", "Matt Smith", "Olivia Colman"],
            director: ["Peter Morgan"],
            platform: "Netflix"
        ),
        ContentItem(
            id: "15",
            type: .series,
            title: "The Witcher",
            releaseDate: "December 20, 2019",
            age: 16,
            rating: Rating(imdb: 8.2),
            genres: ["Fantasy", "Action", "Adventure"],
            summary: "Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.",
            imageAssets: ImageAssets(poster: "thewitcher_poster"),
            cast: ["Henry Cavill", "Anya Chalotra", "Freya Allan"],
            director: ["Lauren Schmidt Hissrich"],
            platform: "Netflix"
        )
    ],
    metadata: Metadata(
        lastUpdated: "February 21, 2025",
        version: "1.5"
    )
)
